# Generated by Django 5.1.6 on 2025-08-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Subcategory Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="downbeats.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_subcategories",
                        to="downbeats.subcategory",
                        verbose_name="Parent Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Soundtrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Soundtrack Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("youtube", "YouTube"), ("spotify", "Spotify")],
                        default="youtube",
                        max_length=50,
                        verbose_name="Origin",
                    ),
                ),
                ("url", models.URLField(verbose_name="Soundtrack URL")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soundtracks",
                        to="downbeats.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soundtracks",
                        to="downbeats.subcategory",
                        verbose_name="Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soundtrack",
                "verbose_name_plural": "Soundtracks",
                "ordering": ["title"],
            },
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "category", "subcategory"),
                name="unique_subcategory_name_per_category_and_parent",
            ),
        ),
    ]
