# Generated by Django 5.1.6 on 2025-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downbeats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundtrack",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="soundtracks/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
    ]
