# Generated by Django 5.1.6 on 2025-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downbeats", "0002_soundtrack_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="subcategories/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
    ]
